function get_departments() {
	return {
		"AST": "Astronomy",
		"ANT": "Anthropology",
		"BIO": "Biology",
		"JBC": "Biology",
		"HSC": "Biomedical Communications",
		"CHM": "Chemistry",
		"JCP": "Chemistry",
		"CPS": "Chemistry",
		"JCB": "Chemistry",
		"CIN": "Cinema Studies",
		"CLA": "Classical Civilization",
		"CCT": "Communication, Culture, Information and Technology",
		"MGD": "Communication, Culture, Information and Technology",
		"WRI": "Communication, Culture, Information and Technology",
		"CSC": "Computer Science",
		"CBJ": "Computer Science",
		"CTE": "Concurrent Teacher Education",
		"DTS": "Diaspora and Transnational Studies",
		"DRE": "Drama",
		"DRS": "Drama",
		"ERS": "Earth Science",
		"ECO": "Economics",
		"EDS": "Education Studies",
		"ENG": "English",
		"ENV": "Environment",
		"JEP": "Environment",
		"FAH": "Fine Art History",
		"FAH": "Fine Art History",
		"VST": "Fine Art History",
		"FAS": "Fine Art Studio",
		"FYE": "First Year Experience",
		"FSC": "Forensic Science",
		"FRE": "French",
		"FSL": "French",
		"LTL": "French",
		"GGR": "Geography",
		"HHS": "Geography",
		"JEG": "Geography",
		"JGE": "Geography",
		"HIS": "History",
		"RLG": "History of Religions",
		"IMI": "Institute for Management and Innovation",
		"ITA": "Italian",
		"GER": "Language Studies",
		"LAT": "Language Studies",
		"SPA": "Language Studies",
		"HIN": "Language Studies",
		"CHI": "Language Studies",
		"PRS": "Language Studies",
		"URD": "Language Studies",
		"ARA": "Language Studies",
		"SAN": "Language Studies",
		"FGI": "Language Studies",
		"HBA": "Language Teaching and Learning: French and Italian",
		"LIN": "Linguistics",
		"JAL": "Linguistics",
		"MGM": "Management",
		"MGT": "Management",
		"MAT": "Mathematics",
		"PHL": "Philosophy",
		"JCP": "Physics",
		"PHY": "Physics",
		"JPE": "Political Science",
		"POL": "Political Science",
		"PSY": "Psychology",
		"SOC": "Sociology",
		"STA": "Statistics",
		"UTM": "Student Development and Transition",
		"VCC": "Visual Culture and Communication",
		"WGS": "Women and Gender Studies"		
	}
}