echo -e "\tUNIX HELP MAIN MENU"
echo "1 -- File and Directory Management Commands"
echo "2 -- Text Processing Commands"
echo "3 -- System Status Commands"
echo "4 -- Exit"
echo -ne "\tEnter your choice:"
