echo -e "\tSYSTEM STATUS COMMANDS"
echo "1 -- Display the current date and time"
echo "2 -- Current disk usage"
echo "3 -- List current local and environmental"
echo "4 -- Display process status information"
echo "5 -- Quit -- Return to Main Menu"
echo -ne "\tEnter your choice:"
