##DATA FOR record.sql##
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (1, 10, 'Beauly', 42, 1, 3, 92.57);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (2, 7, 'D''Aeth', 73, 1, 2, 5.46);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (3, 2, 'Kynd', 2, 4, 4, 4.53);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (4, 1, 'Strongman', 78, 4, 4, 6.25);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (5, 8, 'McKeady', 100, 1, 4, 18.97);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (6, 6, 'Reveland', 51, 3, 2, 79.99);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (7, 2, 'Bonde', 19, 2, 2, 16.49);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (8, 1, 'Eldrett', 24, 2, 2, 8.9);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (9, 4, 'Mazzilli', 50, 4, 1, 41.26);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (10, 3, 'Sherland', 39, 4, 3, 50.46);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (11, 1, 'Nial', 16, 1, 2, 98.26);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (12, 6, 'Hurlston', 43, 3, 4, 16.99);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (13, 9, 'Anscott', 53, 4, 2, 45.62);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (14, 5, 'Lord', 8, 3, 3, 52.04);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (15, 2, 'Fullick', 62, 3, 4, 49.8);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (16, 3, 'Petera', 86, 3, 4, 86.17);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (17, 6, 'Delacroux', 42, 2, 3, 26.45);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (18, 6, 'Gorelli', 52, 3, 1, 65.61);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (19, 6, 'Hilland', 70, 2, 1, 40.01);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (20, 4, 'Points', 87, 3, 1, 97.88);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (21, 7, 'Yetts', 66, 4, 3, 85.25);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (22, 3, 'Mitchel', 46, 3, 2, 14.54);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (23, 2, 'Geroldini', 70, 1, 4, 22.5);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (24, 1, 'Parmley', 36, 4, 2, 99.88);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (25, 8, 'Burcombe', 9, 3, 1, 71.53);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (26, 9, 'McAllaster', 48, 4, 4, 35.37);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (27, 7, 'Buff', 16, 2, 1, 54.3);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (28, 2, 'Esh', 64, 3, 3, 92.48);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (29, 6, 'Edgington', 95, 3, 4, 58.75);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (30, 3, 'Smedley', 74, 4, 3, 33.99);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (31, 9, 'Reubel', 12, 1, 1, 18.14);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (32, 7, 'Livesley', 63, 1, 2, 60.1);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (33, 6, 'Lightoller', 22, 2, 2, 48.92);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (34, 6, 'Bellhouse', 18, 3, 2, 33.9);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (35, 10, 'Pinwill', 17, 4, 2, 87.74);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (36, 8, 'Shortland', 40, 4, 4, 19.91);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (37, 3, 'Mieville', 53, 2, 3, 14.03);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (38, 1, 'D'' Angelo', 40, 3, 4, 38.24);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (39, 9, 'Prandy', 86, 1, 3, 97.66);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (40, 2, 'Blaase', 100, 2, 1, 59.04);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (41, 4, 'Fairfull', 29, 4, 2, 22.5);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (42, 9, 'Sivills', 2, 1, 4, 29.73);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (43, 8, 'Wegner', 29, 1, 1, 20.23);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (44, 9, 'Fallowfield', 67, 2, 1, 55.73);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (45, 2, 'Vitte', 57, 2, 1, 56.91);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (46, 4, 'Schubart', 5, 3, 1, 2.29);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (47, 2, 'Benko', 88, 3, 4, 47.42);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (48, 6, 'Pinnington', 40, 2, 4, 60.48);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (49, 9, 'Doull', 82, 4, 3, 53.66);
insert into record (record_id, report_id, item_name, qty, um_id, type_id, unit_cost) values (50, 1, 'Buckle', 5, 1, 3, 2.28);
##DATA FOR email.sql##
insert into email (user_id, email) values (7, 'acreffield0@xinhuanet.com');
insert into email (user_id, email) values (6, 'lbarnes1@livejournal.com');
insert into email (user_id, email) values (15, 'vdanihel2@shop-pro.jp');
insert into email (user_id, email) values (4, 'aborman3@surveymonkey.com');
insert into email (user_id, email) values (4, 'cmarte4@ft.com');
insert into email (user_id, email) values (9, 'atylor5@alexa.com');
insert into email (user_id, email) values (4, 'dscotney6@bloomberg.com');
insert into email (user_id, email) values (19, 'cbart7@constantcontact.com');
insert into email (user_id, email) values (11, 'gclerk8@java.com');
insert into email (user_id, email) values (8, 'tousby9@netscape.com');
insert into email (user_id, email) values (10, 'lschouta@purevolume.com');
insert into email (user_id, email) values (8, 'swhalleyb@archive.org');
insert into email (user_id, email) values (5, 'kjollandsc@cargocollective.com');
insert into email (user_id, email) values (10, 'alinsteadd@berkeley.edu');
insert into email (user_id, email) values (10, 'mbrame@bloglines.com');
insert into email (user_id, email) values (13, 'bgrimmf@github.io');
insert into email (user_id, email) values (7, 'theikkineng@prweb.com');
insert into email (user_id, email) values (2, 'dabadh@google.nl');
insert into email (user_id, email) values (16, 'vcronkshawi@illinois.edu');
insert into email (user_id, email) values (13, 'fseifertj@youku.com');
##DATA FOR report.sql##
insert into report (user_id, store_id, date) values (18, 8, '2015-08-10');
insert into report (user_id, store_id, date) values (10, 4, '2017-02-14');
insert into report (user_id, store_id, date) values (20, 5, '2016-09-27');
insert into report (user_id, store_id, date) values (13, 1, '2017-07-05');
insert into report (user_id, store_id, date) values (19, 4, '2017-07-05');
insert into report (user_id, store_id, date) values (19, 1, '2017-11-15');
insert into report (user_id, store_id, date) values (5, 3, '2015-01-13');
insert into report (user_id, store_id, date) values (19, 12, '2016-03-17');
insert into report (user_id, store_id, date) values (20, 19, '2017-04-14');
insert into report (user_id, store_id, date) values (9, 18, '2017-12-22');
##DATA FOR store.sql##
insert into store (store_name) values ('Jetwire');
insert into store (store_name) values ('Leexo');
insert into store (store_name) values ('Yodel');
insert into store (store_name) values ('Photojam');
insert into store (store_name) values ('Photolist');
insert into store (store_name) values ('Kare');
insert into store (store_name) values ('Centizu');
insert into store (store_name) values ('Thoughtworks');
insert into store (store_name) values ('Realmix');
insert into store (store_name) values ('Rhyzio');
insert into store (store_name) values ('Feedbug');
insert into store (store_name) values ('Trupe');
insert into store (store_name) values ('Gigaclub');
insert into store (store_name) values ('Browsecat');
insert into store (store_name) values ('Realmix');
insert into store (store_name) values ('Buzzster');
insert into store (store_name) values ('Skibox');
insert into store (store_name) values ('Realbuzz');
insert into store (store_name) values ('DabZ');
insert into store (store_name) values ('Topicware');
##DATA FOR type.sql##
insert into type (type) values ('Other');
insert into type (type) values ('Kids');
insert into type (type) values ('Tools');
insert into type (type) values ('Music');
insert into type (type) values ('Jewelery');
insert into type (type) values ('Sports');
##DATA FOR um.sql##
INSERT INTO um (um) VALUES ('None');
INSERT INTO um (um) VALUES ('ml');
INSERT INTO um (um) VALUES ('L');
INSERT INTO um (um) VALUES ('g');
INSERT INTO um (um) VALUES ('kg');
INSERT INTO um (um) VALUES ('unit');
##DATA FOR users.sql##
insert into users (last_name, first_name, username) values ('Muttock', 'Jerrie', 'jmuttock0');
insert into users (last_name, first_name, username) values ('Arnaudin', 'Mabel', 'marnaudin1');
insert into users (last_name, first_name, username) values ('Letchford', 'Aeriell', 'aletchford2');
insert into users (last_name, first_name, username) values ('Roddie', 'Alfy', 'aroddie3');
insert into users (last_name, first_name, username) values ('Smalley', 'Rosabel', 'rsmalley4');
insert into users (last_name, first_name, username) values ('Elgie', 'Tallulah', 'telgie5');
insert into users (last_name, first_name, username) values ('Duxbury', 'Anna', 'aduxbury6');
insert into users (last_name, first_name, username) values ('Montier', 'Jakie', 'jmontier7');
insert into users (last_name, first_name, username) values ('Beverstock', 'Odele', 'obeverstock8');
insert into users (last_name, first_name, username) values ('Feather', 'Godwin', 'gfeather9');
insert into users (last_name, first_name, username) values ('Skelhorn', 'Hermione', 'hskelhorna');
insert into users (last_name, first_name, username) values ('Skeemor', 'Issie', 'iskeemorb');
insert into users (last_name, first_name, username) values ('Cannicott', 'Celle', 'ccannicottc');
insert into users (last_name, first_name, username) values ('Cleverly', 'Bearnard', 'bcleverlyd');
insert into users (last_name, first_name, username) values ('Guslon', 'Dino', 'dguslone');
insert into users (last_name, first_name, username) values ('Polon', 'Paule', 'ppolonf');
insert into users (last_name, first_name, username) values ('Roswarne', 'Dalis', 'droswarneg');
insert into users (last_name, first_name, username) values ('Rosingdall', 'Ettore', 'erosingdallh');
insert into users (last_name, first_name, username) values ('Degoey', 'Cos', 'cdegoeyi');
insert into users (last_name, first_name, username) values ('Godding', 'Billye', 'bgoddingj');
